export const actions = {
	USER_LOADED: 'USER_LOADED',
	USER_LOAD: 'USER_LOAD',

	AUTH_ERROR: 'AUTH_ERROR',

	LOGIN: 'LOGIN',
	LOGIN_SUCCESS: 'LOGIN_SUCCESS',
	LOGIN_FAIL: 'LOGIN_FAIL',

	LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',

	REGISTER_SUCCESS: 'REGISTER_SUCCESS',
	REGISTER_FAIL: 'REGISTER_FAIL',

	GET_ERRORS: 'GET_ERRORS',
	CLEAR_ERROR: 'CLEAR_ERROR',

	POST_GET: 'POST_GET',
	POST_CREATED: 'POST_CREATED',
	POST_DELETE: 'POST_DELETE',

	USERS_GET: 'USERS_GET',
	USERS_SUB: 'USERS_SUB',
	USERS_FRIEND: 'USERS_FRIEND',
	USERS_UNSUB: 'USERS_UNSUB',
	USERS_UNSUB_FRIEND: 'USERS_UNSUB_FRIEND',

	FRIENDS_GET: 'FRIENDS_GET',

	ALL_POSTS_GET: 'ALL_POSTS_GET',

	CHATROOM_DATA: 'CHATROOM_DATA',
	GET_MESSAGE: 'GET_MESSAGE',

	GET_CHATROOMS: 'GET_CHATROOMS',
}
